"""add user_role to m_users

Revision ID: 01cb6cccf69a
Revises: b17aa5ce3d08
Create Date: 2025-10-22 11:11:55.888577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cb6cccf69a'
down_revision: Union[str, Sequence[str], None] = 'b17aa5ce3d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_users', sa.Column('user_role', sa.Enum('ADMIN', 'USER', name='user_role_enum'), server_default='USER', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_users', 'user_role')
    # ### end Alembic commands ###
