"""allow null for user_name and password

Revision ID: 28d8d7a43604
Revises: 5a6d6b83fc63
Create Date: 2025-12-17 11:36:39.441697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d8d7a43604'
down_revision: Union[str, Sequence[str], None] = '5a6d6b83fc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_users', 'user_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('m_users', 'user_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_users', 'user_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('m_users', 'user_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
