"""add cascade delete to purchase_details

Revision ID: 390314b7e59b
Revises: 
Create Date: 2025-10-14 06:42:41.231200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '390314b7e59b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_companies', 'company_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('m_companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('m_companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'm_companies', ['company_id'])
    # op.alter_column('m_users', 'company_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    op.create_unique_constraint(None, 'm_users', ['user_id'])
    op.create_foreign_key(None, 'm_users', 'm_companies', ['company_id'], ['company_id'])
    op.drop_constraint(op.f('t_purchase_details_sales_id_fkey'), 't_purchase_details', type_='foreignkey')
    op.create_foreign_key(None, 't_purchase_details', 't_sales', ['sales_id'], ['sales_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_purchase_details', type_='foreignkey')
    op.create_foreign_key(op.f('t_purchase_details_sales_id_fkey'), 't_purchase_details', 't_sales', ['sales_id'], ['sales_id'])
    op.drop_constraint(None, 'm_users', type_='foreignkey')
    op.drop_constraint(None, 'm_users', type_='unique')
    # op.alter_column('m_users', 'company_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    op.drop_constraint(None, 'm_companies', type_='unique')
    op.alter_column('m_companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('m_companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('m_companies', 'company_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
