"""Add ondelete cascade to foreign keys

Revision ID: 4b503e800b41
Revises: 8d2e3726ab95
Create Date: 2025-10-22 03:57:32.003646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b503e800b41'
down_revision: Union[str, Sequence[str], None] = '8d2e3726ab95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('t_departments_client_id_fkey'), 't_departments', type_='foreignkey')
    op.create_foreign_key(None, 't_departments', 't_clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('t_sales_client_id_fkey'), 't_sales', type_='foreignkey')
    op.create_foreign_key(None, 't_sales', 't_clients', ['client_id'], ['client_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_sales', type_='foreignkey')
    op.create_foreign_key(op.f('t_sales_client_id_fkey'), 't_sales', 't_clients', ['client_id'], ['client_id'])
    op.drop_constraint(None, 't_departments', type_='foreignkey')
    op.create_foreign_key(op.f('t_departments_client_id_fkey'), 't_departments', 't_clients', ['client_id'], ['client_id'])
    # ### end Alembic commands ###
