"""add user_role nullable true

Revision ID: 5a6d6b83fc63
Revises: 4bfd34dbe284
Create Date: 2025-10-22 11:33:09.293073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a6d6b83fc63'
down_revision: Union[str, Sequence[str], None] = '4bfd34dbe284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_users', 'user_role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='user_role_enum'),
               nullable=False,
               existing_server_default=sa.text("'USER'::user_role_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_users', 'user_role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='user_role_enum'),
               nullable=True,
               existing_server_default=sa.text("'USER'::user_role_enum"))
    # ### end Alembic commands ###
