"""すべてのテーブルでcompany_idをnullable=Trueに

Revision ID: 8d2e3726ab95
Revises: 20bb2c4919c1
Create Date: 2025-10-19 10:34:14.043998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d2e3726ab95'
down_revision: Union[str, Sequence[str], None] = '20bb2c4919c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_companies', 'company_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('m_companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('m_companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'm_companies', ['company_id'])
    op.create_unique_constraint(None, 'm_users', ['user_id'])
    op.drop_constraint(op.f('m_users_company_id_fkey'), 'm_users', type_='foreignkey')
    op.create_foreign_key(None, 'm_users', 'm_companies', ['company_id'], ['company_id'])
    op.add_column('t_clients', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 't_clients', 'm_companies', ['company_id'], ['company_id'])
    op.add_column('t_contacts', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 't_contacts', 'm_companies', ['company_id'], ['company_id'])
    op.add_column('t_departments', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 't_departments', 'm_companies', ['company_id'], ['company_id'])
    op.add_column('t_purchase_details', sa.Column('company_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('t_purchase_details_sales_id_fkey'), 't_purchase_details', type_='foreignkey')
    op.create_foreign_key(None, 't_purchase_details', 'm_companies', ['company_id'], ['company_id'])
    op.create_foreign_key(None, 't_purchase_details', 't_sales', ['sales_id'], ['sales_id'], ondelete='CASCADE')
    op.add_column('t_sales', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 't_sales', 'm_companies', ['company_id'], ['company_id'])
    op.add_column('t_task', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 't_task', 'm_companies', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_task', type_='foreignkey')
    op.drop_column('t_task', 'company_id')
    op.drop_constraint(None, 't_sales', type_='foreignkey')
    op.drop_column('t_sales', 'company_id')
    op.drop_constraint(None, 't_purchase_details', type_='foreignkey')
    op.drop_constraint(None, 't_purchase_details', type_='foreignkey')
    op.create_foreign_key(op.f('t_purchase_details_sales_id_fkey'), 't_purchase_details', 't_sales', ['sales_id'], ['sales_id'])
    op.drop_column('t_purchase_details', 'company_id')
    op.drop_constraint(None, 't_departments', type_='foreignkey')
    op.drop_column('t_departments', 'company_id')
    op.drop_constraint(None, 't_contacts', type_='foreignkey')
    op.drop_column('t_contacts', 'company_id')
    op.drop_constraint(None, 't_clients', type_='foreignkey')
    op.drop_column('t_clients', 'company_id')
    op.drop_constraint(None, 'm_users', type_='foreignkey')
    op.create_foreign_key(op.f('m_users_company_id_fkey'), 'm_users', 'm_companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'm_users', type_='unique')
    op.drop_constraint(None, 'm_companies', type_='unique')
    op.alter_column('m_companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('m_companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('m_companies', 'company_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
