"""add user_role to m_users

Revision ID: b17aa5ce3d08
Revises: 4b503e800b41
Create Date: 2025-10-22 11:03:27.469811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17aa5ce3d08'
down_revision: Union[str, Sequence[str], None] = '4b503e800b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_users', sa.Column('user_role', sa.Enum('ADMIN', 'USER', name='user_role_enum'), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_users', 'user_role')
    # ### end Alembic commands ###
